### ISSUE TITLE
Missing Feature: Rotate Character towards Arbitrary Direction

### ISSUE THREAD

**Issue by Centronias** [PROMETHIA-27/bevy_mod_wanderlust#13]
Hey this plugin is lovely, but it seems to me that it's missing the ability to specify a desired facing direction and smoothly turn towards that direction.
This would be useful for a game like PlateUp! or Overcooked where your character needs to face in specific directions to interact with things in the game world.
I'd originally hacked this turning in by calculating the torque necessary and then applying that as `ControllerInput::custom_torque`, but it was pretty easy to jam into Wanderlust as seen [here](https://github.com/PROMETHIA-27/bevy_mod_wanderlust/compare/master...Centronias:bevy_mod_wanderlust:facing-dir).
I'd put this up as a PR, but it's pretty roughly implemented.

**Comment by davids91** [comment]
Hi! Sorry for the offtopic here, but it seems to me  that you succesfully compiled and ran a project with this plugin! 
 I think there's something stupidly simple I am missing on my setup, but I can't even add the plugin to the simplest of projects... 
 
 https://github.com/PROMETHIA-27/bevy_mod_wanderlust/issues/25

Maybe you know something I don't on how to actually use the plugin?
