### ISSUE TITLE
Missing feature:  `able_to_jump` i.e. `is_grounded` from `ControllerState`

### ISSUE THREAD

**Issue by davids91** [PROMETHIA-27/bevy_mod_wanderlust#27]
I put together something from `ControllerState` and `ControllerService` to signal the start of each jump with  the character

```
struct JumpState{
    is_jumping: bool
}

impl for JumpState{
    fn jump_started(&mut self, state: &ControllerState, settings: &ControllerSettings) -> bool {
        if (0 < controller_state.remaining_jumps
            || controller_state.coyote_timer == controller_settings.coyote_time_duration)
            && controller_state.jump_pressed_last_frame
            && !self.jumping
        {
           self.jumping = true;
           true
        } else {
           self.jumping = false;
           false
        }
    }
}
```

It could be as short as: 

```
fn jump_started(state: &ControllerState, settings: &ControllerSettings) -> bool {
    controller_state.jump_pressed_last_frame && controller_state.is_grounded
}

```

I belive the information is generic enough to be included, and it is calculated in: 
https://github.com/PROMETHIA-27/bevy_mod_wanderlust/blob/63fef1c9381a1c6d389091de77bef2eec6f256e8/src/systems.rs#L101

**Comment by PROMETHIA-27** [comment]
Created a PR. Will wait for aceeri to review it if they get around to it in a few days, otherwise will come back to it after I'm done with my current project and make sure it works as intended and merge.
