### ISSUE TITLE
Jitter regression after 0.8 update

### ISSUE THREAD

**Issue by PROMETHIA-27** [PROMETHIA-27/bevy_mod_wanderlust#4]
Something seems to have changed in bevy_rapier3d to cause jitter in the FPS example when running into walls again. Will have to investigate.
Also there seems to be an additional debug render mesh that wasn't there before? A bit obnoxious.

**Comment by Aceeri** [comment]
should be fixed with https://github.com/dimforge/bevy_rapier/pull/248 but need to wait for a new release of bevy_rapier
